from __future__ import annotations

DATASET_VERSION = "2026.08"

CATALOG = [
    # GOODS (HSN)
    {
        "code": "9403",
        "kind": "HSN",
        "name": "Office furniture (chairs, desks, tables)",
        "aliases": ["furniture", "chair", "desk", "table", "office chair", "workstation"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "94",
        "heading": "9403",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "8471",
        "kind": "HSN",
        "name": "Computers, laptops, servers, and data processing units",
        "aliases": ["computer", "laptop", "server", "macbook", "pc", "desktop"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "84",
        "heading": "8471",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "8479",
        "kind": "HSN",
        "name": "Industrial plant, factory machinery, and capital goods",
        "aliases": ["machine", "machinery", "factory machine", "plant", "equipment", "industrial machine", "manufacturing machine", "lathe", "press", "cnc", "capital goods"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "84",
        "heading": "8479",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "8517",
        "kind": "HSN",
        "name": "Smartphones, networking routers, and telecom equipment",
        "aliases": ["smartphone", "phone", "mobile", "router", "iphone", "android"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "85",
        "heading": "8517",
        "effective_from": "2020-04-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "8703",
        "kind": "HSN",
        "name": "Motor cars and passenger vehicles",
        "aliases": ["car", "motor car", "vehicle", "automobile", "suv", "sedan"],
        "rate": 28.0,
        "itc": False,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule IV",
        "chapter": "87",
        "heading": "8703",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 15.0,
        "rcm_applicable": False,
        "blocked_reason": "Section 17(5)(a) of CGST Act — Blocked credit on motor vehicles for seating <= 13 persons unless used for passenger transport or driving training",
    },
    {
        "code": "2106",
        "kind": "HSN",
        "name": "Food preparations, restaurant food, and outdoor catering",
        "aliases": ["food", "catering", "restaurant", "dinner", "lunch", "snacks", "beverages"],
        "rate": 5.0,
        "itc": False,
        "source": "Notification No. 11/2017-Central Tax (Rate) as amended",
        "chapter": "21",
        "heading": "2106",
        "effective_from": "2017-11-15",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "Section 17(5)(b)(i) — Input tax credit explicitly blocked on food, beverages, and outdoor catering",
    },
    {
        "code": "2501",
        "kind": "HSN",
        "name": "Portland cement and building materials",
        "aliases": ["cement", "portland", "concrete"],
        "rate": 28.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule IV",
        "chapter": "25",
        "heading": "2501",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "7210",
        "kind": "HSN",
        "name": "Steel and coated flat-rolled iron products",
        "aliases": ["steel", "iron", "sheet", "tmt"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule III",
        "chapter": "72",
        "heading": "7210",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "3004",
        "kind": "HSN",
        "name": "Medicines and pharmaceutical preparations",
        "aliases": ["medicine", "pharma", "drugs", "tablets", "syrup"],
        "rate": 12.0,
        "itc": True,
        "source": "Notification No. 01/2017-Central Tax (Rate), Schedule II",
        "chapter": "30",
        "heading": "3004",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "4901",
        "kind": "HSN",
        "name": "Printed books, brochures, leaflets",
        "aliases": ["book", "printed book", "magazines", "textbook"],
        "rate": 0.0,
        "itc": False,
        "source": "Notification No. 02/2017-Central Tax (Rate) [Exempt]",
        "chapter": "49",
        "heading": "4901",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "Exempt supply under Section 11 of CGST Act",
    },
    # SERVICES (SAC)
    {
        "code": "998313",
        "kind": "SAC",
        "name": "IT and software development consultancy services",
        "aliases": ["software", "it services", "app development", "coding", "web development", "tech consulting"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate), Heading 9983",
        "chapter": "99",
        "heading": "9983",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "998314",
        "kind": "SAC",
        "name": "Information technology infrastructure, hosting, and cloud services",
        "aliases": ["cloud", "hosting", "aws", "azure", "server hosting", "saas"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate), Heading 9983",
        "chapter": "99",
        "heading": "9983",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "998221",
        "kind": "SAC",
        "name": "Accounting, auditing, and bookkeeping services",
        "aliases": ["accounting", "audit", "bookkeeping", "ca services", "tax filing"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate), Heading 9982",
        "chapter": "99",
        "heading": "9982",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
    {
        "code": "998231",
        "kind": "SAC",
        "name": "Legal advisory and representation services",
        "aliases": ["legal", "lawyer", "advocate", "litigation"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 13/2017-Central Tax (Rate) [RCM Applicable]",
        "chapter": "99",
        "heading": "9982",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": True,
        "blocked_reason": "Recipient liable to pay GST under Reverse Charge Mechanism (RCM)",
    },
    {
        "code": "996511",
        "kind": "SAC",
        "name": "Goods transport agency (GTA) freight services",
        "aliases": ["transport", "freight", "gta", "logistics", "courier", "truck"],
        "rate": 5.0,
        "itc": False,
        "source": "Notification No. 11/2017-Central Tax (Rate), Entry 9(iii)",
        "chapter": "99",
        "heading": "9965",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": True,
        "blocked_reason": "ITC not available when GTA elects 5% rate under RCM",
    },
    {
        "code": "998411",
        "kind": "SAC",
        "name": "Advertising, digital marketing, and media placement services",
        "aliases": ["advertising", "marketing", "ads", "digital marketing", "google ads", "seo"],
        "rate": 18.0,
        "itc": True,
        "source": "Notification No. 11/2017-Central Tax (Rate), Heading 9984",
        "chapter": "99",
        "heading": "9984",
        "effective_from": "2017-07-01",
        "effective_to": None,
        "cess_rate": 0.0,
        "rcm_applicable": False,
        "blocked_reason": "",
    },
]


def find_candidates(text: str) -> list[dict]:
    q = text.lower()
    scored = []
    for item in CATALOG:
        score = sum(1 for token in item["aliases"] if token in q)
        if score > 0:
            scored.append((score, item))
    return [item for _, item in sorted(scored, key=lambda x: x[0], reverse=True)]


def by_code(code: str) -> dict | None:
    c = str(code).strip()
    return next((item for item in CATALOG if item["code"] == c), None)
